services:
  mongodb:
    image: mongo:4.4.6-bionic
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env.development
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    restart: unless-stopped
